// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Dxj2beLXPR-ibYVQlcC-Wy0CNxlAmtg',
    appId: '1:211416057240:web:e4ae00b82dbd3d9a2517ed',
    messagingSenderId: '211416057240',
    projectId: 'push-98ccd',
    authDomain: 'push-98ccd.firebaseapp.com',
    storageBucket: 'push-98ccd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB55IU5jJ02Q6Mv_jYVg67RDnKb_a_qQN0',
    appId: '1:211416057240:android:c1bd6578d26359302517ed',
    messagingSenderId: '211416057240',
    projectId: 'push-98ccd',
    storageBucket: 'push-98ccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1ixMstIvAXf9fIy1WHbxfQKFu21-dGlo',
    appId: '1:211416057240:ios:4a80c2c86287a71d2517ed',
    messagingSenderId: '211416057240',
    projectId: 'push-98ccd',
    storageBucket: 'push-98ccd.appspot.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1ixMstIvAXf9fIy1WHbxfQKFu21-dGlo',
    appId: '1:211416057240:ios:4a80c2c86287a71d2517ed',
    messagingSenderId: '211416057240',
    projectId: 'push-98ccd',
    storageBucket: 'push-98ccd.appspot.com',
    iosBundleId: 'com.example.push',
  );
}
